name: Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - "*.md"
      - "docs/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    if: github.repository_owner == 'wso2'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 21.0.3
          cache: gradle

      - name: Change to Timestamped Version
        run: |
          startTime=$(TZ="Asia/Kolkata" date +'%Y%m%d-%H%M00')
          latestCommit=$(git log -n 1 --pretty=format:"%h")
          VERSION=$(grep -w 'version' gradle.properties | cut -d= -f2 | sed -E 's/-(SNAPSHOT|[0-9]{8}-[0-9]{6}-[a-z0-9]+)$//')
          updatedVersion=$VERSION-$startTime-$latestCommit
          echo $updatedVersion
          sed -i "s/version=\(.*\)/version=$updatedVersion/g" gradle.properties

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        env:
          packageUser: ${{ secrets.BALLERINA_BOT_USERNAME }}
          packagePAT: ${{ secrets.BALLERINA_BOT_TOKEN }}
          publishUser: ${{ secrets.BALLERINA_BOT_USERNAME }}
          publishPAT: ${{ secrets.BALLERINA_BOT_TOKEN }}
        run: |
          ./gradlew publish --no-daemon --scan

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./compiler-plugin-tests/build/reports/jacoco/test/jacocoTestReport.xml
          flags: unittests
          name: main-branch-coverage

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ballerina-runtime
          path: target/ballerina-runtime/
